"""Add check_in_status to Attendance model

Revision ID: 532dd2c9e86c
Revises: dd265e5568d2
Create Date: 2025-10-31 21:36:27.848402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532dd2c9e86c'
down_revision = 'dd265e5568d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('check_in_status')

    # ### end Alembic commands ###
